export const FETCH_TOKENS = 'FETCH_TOKENS';
export const FETCH_FEED = 'FETCH_FEED';
// POST ACTIONS
export const NEW_POST = 'NEW_POST';
export const FETCH_CURRENT_USER_PROFILE = 'FETCH_CURRENT_USER_PROFILE';